### PR TITLE
WIP for new account region

### PR DESCRIPTION
**Pull request by YajB**
# What changed
Per[ slack conversation](https://logzio.slack.com/archives/C09BN38JC/p1639930519046800), added new region to list in topic https://docs.logz.io/user-guide/accounts/account-region.html

Preview: https://deploy-preview-1584--logz-docs.netlify.app/user-guide/accounts/account-region.html#available-regions

Questions for @doron-logzio : 

1. Which cloud?
2. Does ap-northeast1 support Prometheus metrics ?
3. Please help me complete the table: 
    -  Official region name: Asia Pacific (North East) or Asia Pacific (Japan)?
    - Cloud: AWS or Azure?
    - Account host: app-jp.logz.io
    - Listener: listener-jp.logz.io
    - API: api-jp.logz.io
    - Code: jp
    - Region “slug”: ap-northeast1

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

### CODE REVIEW

**Review by doron-logzio — COMMENTED** [review]
I think that in the spirit of Asia Pacific (Sydney) Asia Pacific (Japan) is consistent.
That said, we are currently planning to open the region for vmware only, so I would wait with this change for a few days, until we approve the region for all customers for all products

**Comment by YajB** [comment]
> I think that in the spirit of Asia Pacific (Sydney) Asia Pacific (Japan) is consistent. That said, we are currently planning to open the region for vmware only, so I would wait with this change for a few days, until we approve the region for all customers for all products

No problem! I figured I might as well capture the change now, make it available for review/feedback, and then publish on your say-so.

**Review by nzyoni — COMMENTED** [review]
just commenting here so GitHub bot will stop notify me about this pr

**Comment by Simplychee** [comment]
on hold

**Pull request closed without merging**
