### PR TITLE
comment out custom config options

### PR DESCRIPTION
**Pull request by imnotashrimp**
### What changed

Fixes mistakes found in #280 

Commented out custom configuration instructions. These were incomplete and unusable in their current form. Will add in a future PR.

## Pages to review

- [ ] https://deploy-preview-281--logz-docs.netlify.com/shipping/log-sources/elastic-kubernetes-service.html
- [ ] https://deploy-preview-281--logz-docs.netlify.com/shipping/log-sources/kubernetes.html

**Notes for reviewers**: none

## Remaining work

- [ ] Copy Review

## Post launch

**Do not remove** - To be completed by the docs team upon merge:
- [ ] Teams to update with the new information: Integrations
- [ ] Sync with readme in the logzio-k8s repo
- [ ] Replace instructions in the app:
  - [ ] EKS
  - [ ] Kubernetes

### CODE REVIEW

**Comment by yyyogev** [comment]
Also, I think the file should be named something like kube-fluentd-rbac.yaml

**Comment by imnotashrimp** [comment]
> Also, I think the file should be named something like kube-fluentd-rbac.yaml

That's up to you in the logzio-k8s project. Let's push this through and make the change later if needed.

**Comment by imnotashrimp** [comment]
> Looks good!
> So this is EKS only?

No, this is both EKS and Kubernetes.

**Comment by idohalevi** [comment]
@imnotashrimp @yyyogev Not sure I agree with deleting the configuration table. 
Some will want to modify the values depending on the number of logs they send. Let's talk tomorrow and try to find the middle ground

**Comment by imnotashrimp** [comment]
@idohalevi Not deleted, just commented out until we can come back and provide instructions for how to deploy the custom configuration. As it was written today, user would be unable to deploy a custom configuration.

**Comment by idohalevi** [comment]
@imnotashrimp Users can it's just not explained well. We have most of the parameters in the table in our fluent.conf file and if someone wants to change it and know how he won't have documentation for those variables

**Comment by idohalevi** [comment]
@imnotashrimp Hiding is never the answer...

**Comment by imnotashrimp** [comment]
@idohalevi The documentation was incomplete. For now, the user is offered default config. When we can document how to deploy a custom configuration, let's add it back in.

**Pull request merged**
