### PR TITLE
Added Openshift integration

### PR DESCRIPTION
**Pull request by nico-shishkin**
# What changed

https://deploy-preview-1408--logz-docs.netlify.app/shipping/log-sources/openshift.html#default 

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

### CODE REVIEW

**Review by Doron-Bargo — APPROVED** [review]
lgtm
Lets wait @mirii1994 to approve it as well

**Comment by Doron-Bargo** [comment]
Please add tag:  - container so customers can easily find it

**Comment by Doron-Bargo** [comment]
And remove tag "agent"

**Review by mirii1994 — APPROVED** [review]
Great job!
Like @Doron-Bargo said, it should be under containers, not agents :)

**Pull request merged**
