### PR TITLE
simplify winlogbeat instructions

### PR DESCRIPTION
**Pull request by imnotashrimp**
# What changed

Simplified shipping instructions for winlogbeat. Fixes processors conflict reported in #328 

----

## Pages to review

- [x] https://deploy-preview-329--logz-docs.netlify.com/shipping/log-sources/active-directory-winserver.html
- [x] https://deploy-preview-329--logz-docs.netlify.com/shipping/log-sources/windows.html

## Remaining work

- [ ] Technical review
- [x] Copy Review

## Post launch

**Do not remove** - To be completed by the docs team upon merge:

- [x] Teams to update with the new information:
- [ ] Update these log shipping pages in the app:
  - [ ] https://app.logz.io/#/dashboard/data-sources/Windows

### CODE REVIEW

**Comment by imnotashrimp** [comment]
@zdhamilton Take a look and see if this works for you

**Comment by imnotashrimp** [comment]
@schwin007 Please take another look.

I'll open a different PR to add the port numbers back in (across all shipping docs)

**Comment by imnotashrimp** [comment]
@zdhamilton Right you are. That's my fault for opening a PR when I should have been in bed 😬

Please take another look when you have a moment

**Comment by zdhamilton** [comment]
This could just be nitpicky so totally disregard if it is. 

The language in 'https://deploy-preview-329--logz-docs.netlify.com/shipping/log-sources/windows.html' gets a little redundant in the 3rd step. "If Logz.io isn't the output, set it now" and "Winlogbeat can only have one output, so remove any other output entries" seem redundant to me since you had them start from scratch in step 1. I think these cases would be never happen starting with an empty config. I think it's the same in the AD doc too. 

Once again, this could be way too picky so feel free to disregard entirely.

**Comment by imnotashrimp** [comment]
> This could just be nitpicky so totally disregard if it is.
> 
> The language in 'https://deploy-preview-329--logz-docs.netlify.com/shipping/log-sources/windows.html' gets a little redundant in the 3rd step. "If Logz.io isn't the output, set it now" and "Winlogbeat can only have one output, so remove any other output entries" seem redundant to me since you had them start from scratch in step 1. I think these cases would be never happen starting with an empty config. I think it's the same in the AD doc too.
> 
> Once again, this could be way too picky so feel free to disregard entirely.

Not nitpicky at all!

The doc was revised to accommodate both a fresh installation and an existing configuration. Step 1 now says to start with a new file if you have the default config. I did this to bring Winlogbeat in line with the way we handle Filebeat.

**Comment by zdhamilton** [comment]
> > This could just be nitpicky so totally disregard if it is.
> > The language in 'https://deploy-preview-329--logz-docs.netlify.com/shipping/log-sources/windows.html' gets a little redundant in the 3rd step. "If Logz.io isn't the output, set it now" and "Winlogbeat can only have one output, so remove any other output entries" seem redundant to me since you had them start from scratch in step 1. I think these cases would be never happen starting with an empty config. I think it's the same in the AD doc too.
> > Once again, this could be way too picky so feel free to disregard entirely.
> 
> Not nitpicky at all!
> 
> The doc was revised to accommodate both a fresh installation and an existing configuration. Step 1 now says to start with a new file if you have the default config. I did this to bring Winlogbeat in line with the way we handle Filebeat.

Ahh got it. Then In that case it looks great!

**Pull request merged**
