### PR TITLE
S3 bucket - image update

### PR DESCRIPTION
**Pull request by YajB**
# What changed
updated images  after step 6: https://deploy-preview-1105--logz-docs.netlify.app/shipping/log-sources/s3-bucket.html

----

## Pages to review

- LinkToPage1
- LinkToPage2

## Remaining work

- [ ] Technical review
- [ ] Copy Review
- [ ] Redirects: 

## Post launch

To be completed by the docs team upon merge:

- [ ] Teams to update with the new information:
- [ ] Replace original content on the support portal with 'this page has been moved to ...' - paste the URL
- [ ] Update these log shipping pages in the app: - paste the URL

### CODE REVIEW

**Comment by nofar9792** [comment]
we need to hide the data, right?

**Comment by nofar9792** [comment]
and do you know if we need "IAM role configuration" or "Key access configuration"?

**Comment by YajB** [comment]
> and do you know if we need "IAM role configuration" or "Key access configuration"?

I don't know how to answer that question.

**Comment by nofar9792** [comment]
> > and do you know if we need "IAM role configuration" or "Key access configuration"?
> 
> I don't know how to answer that question.

we recommend IAM, and now it's IAM so let's stay with that :)

**Pull request merged**
